# Generated by Django 4.1 on 2022-09-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_alter_productcategory_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='category',
            field=models.ManyToManyField(to='product_module.productcategory', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='عنوان (url)'),
        ),
    ]
