# Generated by Django 4.1 on 2022-09-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_productview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productview',
            old_name='user_id',
            new_name='user',
        ),
    ]
