# Generated by Django 4.1 on 2022-08-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_footercategorylink_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='image_map_address',
            field=models.ImageField(blank=True, null=True, upload_to='images/site-setting', verbose_name='تصویر نقشه ادرس شما'),
        ),
    ]
