# Generated by Django 4.1 on 2022-08-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_sitesetting_image_map_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اسلایدر')),
                ('descriptions', models.TextField(verbose_name='توضیحات')),
                ('url_title', models.CharField(max_length=200, verbose_name='عنوان لینک')),
                ('url', models.URLField(verbose_name='لینک')),
                ('image', models.ImageField(upload_to='images/slider')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
