# Generated by Django 4.1 on 2022-09-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0009_alter_adsbanners_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsbanners',
            name='is_active',
            field=models.BooleanField(verbose_name=' فعال / غیرفعال'),
        ),
    ]
