# Generated by Django 4.1 on 2022-08-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='نام')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=400, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده/ نشده')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('response', models.TextField(blank=True, null=True, verbose_name='متن پاسخ')),
            ],
            options={
                'verbose_name': 'تماس با ما ',
                'verbose_name_plural': ' لیست تماس با ما ',
            },
        ),
    ]
