# Generated by Django 4.1 on 2022-08-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0002_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product', verbose_name='تصویر محصول'),
        ),
        migrations.AlterField(
            model_name='uploaded',
            name='image',
            field=models.ImageField(upload_to='uploads/images'),
        ),
    ]
