# Generated by Django 4.1 on 2022-08-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0003_contactus_image_alter_uploaded_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='image',
        ),
    ]
