# Generated by Django 4.1 on 2022-08-31 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0010_articlecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_module.articlecomment', verbose_name='پاسخ'),
        ),
    ]
