# Generated by Django 4.1 on 2022-08-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_alter_user_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=20, null=True, verbose_name='تصویر آواتار'),
        ),
    ]
