# Generated by Django 4.1 on 2022-08-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_user_about_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(max_length=20, null=True, upload_to='', verbose_name='تصویر آواتار'),
        ),
    ]
