# Generated by Django 4.1 on 2022-09-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0009_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile', verbose_name='تصویر آواتار'),
        ),
    ]
